DROP TABLE ERS_REIMBURSEMENT CASCADE;
DROP TABLE ERS_USERS CASCADE;
DROP TABLE ERS_REIMBURSEMENT_STATUS;
DROP TABLE ERS_REIMBURSEMENT_TYPE;
DROP TABLE ERS_USER_ROLES;

CREATE TABLE ERS_REIMBURSEMENT(
	REIMB_ID SERIAL PRIMARY KEY,
	REIMB_AMOUNT NUMERIC NOT NULL,
	REIMB_SUBMITTED TIMESTAMP NOT NULL,
	REIMB_RESOLVED TIMESTAMP,
	REIMB_DESCRIPTION VARCHAR(250),
	REIMB_RECEIPT BYTEA,
	REIMB_AUTHOR INTEGER REFERENCES ERS_USERS (ERS_USERS_ID)NOT NULL,
	REIMB_RESOLVER INTEGER REFERENCES ERS_USERS (ERS_USERS_ID),
	REIMB_STATUS_ID INTEGER REFERENCES ERS_REIMBURSEMENT_STATUS (REIMB_STATUS_ID) NOT NULL,
	REIMB_TYPE_ID INTEGER REFERENCES ERS_REIMBURSEMENT_TYPE (REIMB_TYPE_ID) NOT NULL
)

CREATE TABLE ERS_USERS(
	ERS_USERS_ID SERIAL PRIMARY KEY,
	ERS_USERNAME VARCHAR(50) UNIQUE NOT NULL,
	ERS_PASSWORD VARCHAR(50) NOT NULL,
	ERS_FIRST_NAME VARCHAR(50) NOT NULL,
	ERS_LAST_NAME VARCHAR(50) NOT NULL,
	ERS_EMAIL VARCHAR(50) UNIQUE NOT NULL,
	ERS_ROLE_ID INT REFERENCES ERS_USER_ROLES (ERS_USER_ROLE_ID) NOT NULL
)

CREATE TABLE ERS_REIMBURSEMENT_STATUS(
	REIMB_STATUS_ID SERIAL PRIMARY KEY,
	REIMB_STATUS VARCHAR(10) NOT NULL
)
	
CREATE TABLE ERS_REIMBURSEMENT_TYPE(
	REIMB_TYPE_ID SERIAL PRIMARY KEY,
	REIMB_TYPE VARCHAR(10) NOT NULL
)
	
CREATE TABLE ERS_USER_ROLES(
	ERS_USER_ROLE_ID SERIAL PRIMARY KEY,
	USER_ROLE VARCHAR(10) NOT NULL
)